## Ansible example inventory file
# This file is loaded

all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 35.236.65.239 # Change this IP
          ansible_user: chrisnovak_google_com # Change to user to ssh with
    dbservers:
      hosts:
        db1:
          ansible_host: 35.236.65.239 # Change this IP
          ansible_user: chrisnovak_google_com # Change to user to ssh with