---
roles:
  - name: geerlingguy.php
    version: 4.2.0
  - name: geerlingguy.nginx
    version: 2.7.0
  - name: geerlingguy.repo-remi
    version: 1.2.0
  - name: geerlingguy.repo-epel
    version: 1.3.0
  - name: geerlingguy.drupal
    src: https://github.com/mhitza/ansible-role-drupal
    version: 3.0.2
  - name: geerlingguy.mysql
    version: 3.1.0
  - name: geerlingguy.composer
    version: 1.7.6
  - name: geerlingguy.git
    version: 3.0.0
